---
title: "Save data"
author: "Stefano Coretta"
date: "20/05/2019"
output: 
  html_document: 
    highlight: tango
    number_sections: yes
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
knitr::opts_knit$set(root.dir = here::here())
library(tidyverse)
library(usethis)
```

# Read data

```{r read}
stimuli <- read_csv("./data-raw/datasets/stimuli.csv")

eng_durations <- read_csv("./data-raw/datasets/english-durations.csv", na = "--undefined--") %>%
  left_join(y = stimuli) %>%
  mutate(
    sentence_duration = sentence_off - sentence_ons,
    rel_rel = (c2_rel - c1_rel) * 1000,
    v1_duration = (v1_off - v1_ons) * 1000,
    c2_clos_duration = (c2_rel - v1_off) * 1000,
    voicing = factor(voicing, levels = c("voiceless", "voiced")),
    num_syl = factor(num_syl, levels = c("di", "mono")),
    place = factor(place, levels = c("velar", "labial")),
    vowel = factor(vowel, levels = c("ar", "er", "ee")),
    c2 = factor(c2, levels = c("k", "g", "p", "b")),
    speech_rate = ifelse(num_syl == "mono", 6 / sentence_duration, 7 / sentence_duration),
    speech_rate_c = speech_rate - mean(speech_rate)
  ) %>%
  mutate_if(is.character, as.factor)
```

# Use data

```{r use-data}
use_data(eng_durations, overwrite = TRUE)
```

Save aggregated csv file for use in other software.

```{r aggregate}
write_csv(eng_durations, path = "./data-raw/aggregated/eng-durations.csv")
```

